name: web3dart_cubealgos
description: Dart library to connect to Ethereum clients. Send transactions and interact with smart contracts!
version: 1.0.0
homepage: https://cubealgos.org
repository: https://github.com/cubealgos/web3dart_cubealgos

environment:
  sdk: ^3.7.2

dependencies:
  pointycastle: 4.0.0
  typed_data: ^1.3.2
  convert: ^3.1.1
  async: ^2.11.0
  json_rpc_2: ^3.0.3
  http: ^1.3.0

dev_dependencies:
  test: ^1.24.6
  lints: ^3.0.0
